/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar ingredientes del catálogo
         * @description Devuelve todos los ingredientes disponibles con id, nombre en español y categoría. Útil para construir un selector de dislikes en el frontend.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de ingredientes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": "chicken_breast",
                         *         "name": "Pechuga de pollo",
                         *         "category": "protein",
                         *         "categoryLabel": "Proteínas",
                         *         "dietaryTags": [
                         *           "gluten_free",
                         *           "lactose_free"
                         *         ]
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["IngredientSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients/dietary-tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar tags dietéticos disponibles
         * @description Devuelve todos los tags de dieta con su id y etiqueta en español. Útil para construir un selector de preferencias del usuario.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de tags dietéticos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example [
                         *       {
                         *         "id": "vegan",
                         *         "label": "Vegano"
                         *       },
                         *       {
                         *         "id": "gluten_free",
                         *         "label": "Sin gluten"
                         *       }
                         *     ]
                         */
                        "application/json": components["schemas"]["DietaryTagOption"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar recetas del catálogo
         * @description Devuelve todas las recetas pre-armadas. Se puede filtrar por tag dietético. Cada receta ya contiene macros calculados y puede usarse directamente en `POST /recipes/adapt`.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filtrar por tag dietético */
                    dietaryTag?: components["schemas"]["DietaryTag"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de recetas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recipe"][];
                    };
                };
                /** @description Query inválida (dietaryTag desconocido) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener una receta por ID
         * @description Devuelve una receta completa del catálogo lista para enviar a `POST /recipes/adapt`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID de la receta (ej: arroz_con_pollo) */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Receta encontrada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Recipe"];
                    };
                };
                /** @description Receta no encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Receta no encontrada"
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recipes/adapt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Adaptar receta a una condición médica
         * @description Recibe una receta y una condición médica. Si la receta ya es apta, la devuelve sin cambios. Si no, consulta el LLM (con cache Redis) para sugerir reemplazos de ingredientes y aplica los válidos de forma determinística.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "conditionId": "diabetes",
                     *       "targetServings": 4,
                     *       "dislikes": [
                     *         "broccoli"
                     *       ],
                     *       "recipe": {
                     *         "id": "arroz_con_pollo",
                     *         "name": "Arroz con pollo y brócoli",
                     *         "baseServings": 2,
                     *         "currentServings": 2,
                     *         "cookingTimeMinutes": 35,
                     *         "cookingType": "salteado",
                     *         "dietaryTags": [
                     *           "gluten_free",
                     *           "lactose_free"
                     *         ],
                     *         "ingredients": [
                     *           {
                     *             "ingredientId": "chicken_breast",
                     *             "grams": 300
                     *           },
                     *           {
                     *             "ingredientId": "white_rice_cooked",
                     *             "grams": 300
                     *           },
                     *           {
                     *             "ingredientId": "broccoli",
                     *             "grams": 200
                     *           },
                     *           {
                     *             "ingredientId": "onion",
                     *             "grams": 80
                     *           },
                     *           {
                     *             "ingredientId": "bell_pepper",
                     *             "grams": 100
                     *           },
                     *           {
                     *             "ingredientId": "olive_oil",
                     *             "grams": 15
                     *           }
                     *         ],
                     *         "steps": [
                     *           {
                     *             "order": 1,
                     *             "description": "Cortar el pollo en cubos y salpimentar."
                     *           },
                     *           {
                     *             "order": 2,
                     *             "description": "Sellar el pollo en aceite de oliva."
                     *           },
                     *           {
                     *             "order": 3,
                     *             "description": "Saltear cebolla y morrón 3 min."
                     *           },
                     *           {
                     *             "order": 4,
                     *             "description": "Agregar brócoli y cocinar 4 min."
                     *           },
                     *           {
                     *             "order": 5,
                     *             "description": "Incorporar el arroz y el pollo. Mezclar 2 min."
                     *           }
                     *         ],
                     *         "macros": {
                     *           "total": {
                     *             "calories": 847.4,
                     *             "protein": 110.9,
                     *             "fat": 26.4,
                     *             "carbohydrates": 55.2
                     *           },
                     *           "perServing": {
                     *             "calories": 423.7,
                     *             "protein": 55.5,
                     *             "fat": 13.2,
                     *             "carbohydrates": 27.6
                     *           }
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["AdaptRequest"];
                };
            };
            responses: {
                /** @description Receta adaptada exitosamente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AdaptedRecipeResult"];
                    };
                };
                /** @description Body inválido */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationError"];
                    };
                };
                /** @description Condición médica no encontrada */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "Condición médica no encontrada: \"unknown\""
                         *     }
                         */
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Rate limit superado (5 req / 10 min por IP) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RateLimitError"];
                    };
                };
                /** @description Error interno del servidor */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Servidor activo */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdaptRequest: {
            recipe: components["schemas"]["Recipe"];
            /**
             * @description ID de la condición médica del paciente
             * @enum {string}
             */
            conditionId: "diabetes" | "hypertension" | "celiac";
            /** @description IDs de ingredientes que el paciente no quiere */
            dislikes?: string[];
            /** @description Escalar la receta a N porciones antes de adaptar */
            targetServings?: number;
        };
        IngredientSummary: {
            /** @example chicken_breast */
            id: string;
            /** @example Pechuga de pollo */
            name: string;
            /** @example protein */
            category: string;
            /** @example Proteínas */
            categoryLabel: string;
            dietaryTags: components["schemas"]["DietaryTag"][];
        };
        DietaryTagOption: {
            id: components["schemas"]["DietaryTag"];
            /** @example Sin gluten */
            label: string;
        };
        /**
         * @description Tag dietético de un ingrediente o receta
         * @enum {string}
         */
        DietaryTag: "vegan" | "vegetarian" | "keto" | "low_carb" | "gluten_free" | "lactose_free";
        Recipe: {
            id: string;
            name: string;
            baseServings: number;
            currentServings: number;
            cookingTimeMinutes: number;
            /** @example salteado */
            cookingType: string;
            /** @description Tags dietéticos que aplican a la receta (intersección de los tags de todos sus ingredientes) */
            dietaryTags: components["schemas"]["DietaryTag"][];
            ingredients: components["schemas"]["RecipeIngredient"][];
            steps: components["schemas"]["RecipeStep"][];
            macros: components["schemas"]["RecipeMacros"];
        };
        RecipeIngredient: {
            /** @example chicken_breast */
            ingredientId: string;
            /** @example 300 */
            grams: number;
        };
        RecipeStep: {
            order: number;
            description: string;
        };
        Macros: {
            calories: number;
            protein: number;
            fat: number;
            carbohydrates: number;
        };
        RecipeMacros: {
            total: components["schemas"]["Macros"];
            perServing: components["schemas"]["Macros"];
        };
        AdaptedRecipeResult: {
            recipe: components["schemas"]["Recipe"];
            /** @description Cambios aplicados (reemplazos del LLM + ajustes técnicos) */
            technicalChanges: string[];
            /** @description Sugerencias del LLM que no se aplican automáticamente */
            optionalSuggestions: string[];
            /** @description Advertencias no fatales: dislikes presentes, reemplazos rechazados, violaciones residuales */
            warnings: string[];
        };
        Error: {
            error?: string;
        };
        ValidationError: {
            /** @example Body inválido */
            error?: string;
            details?: {
                [key: string]: string[];
            };
        };
        RateLimitError: {
            /** @example Demasiadas solicitudes. Intentá de nuevo más tarde. */
            error?: string;
            /** @example 547 */
            retryAfterSeconds?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
